### PR TITLE
Merge pull request #1 from jlmess77/master

### PR DESCRIPTION
**Pull request by ericbsd**
update

### CODE REVIEW

**Comment by kwm81** [comment]
You nukes the distinfo files, we really want those. Can you put them back please?

**Comment by ericbsd** [comment]
I nuke the dist file?

On Sat, Mar 8, 2014 at 3:24 AM, Koop Mast notifications@github.com wrote:

> You nukes the distinfo files, we really want those. Can you put them back
> please?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/jlmess77/mate-ports/pull/6#issuecomment-37091474
> .

## 

_Eric Turgeon__GhostBSD project_
Office location:
1-11 connaught
Moncton NB Canada
www.ghostbsd.org http://www.ghostbsd.org/

**Comment by kwm81** [comment]
distinfo missing.

**Comment by ericbsd** [comment]
good thanks

On Sat, Mar 8, 2014 at 9:17 AM, Koop Mast notifications@github.com wrote:

> distinfo missing.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/jlmess77/mate-ports/pull/6#issuecomment-37097374
> .

## 

_Eric Turgeon__GhostBSD project_
Office location:
1-11 connaught
Moncton NB Canada
www.ghostbsd.org http://www.ghostbsd.org/

**Comment by jlmess77** [comment]
The x11-fm/caja-dropbox in pull request doesn't look right. It's incomplete. For example, the pkg-descr and pkg-plist don't look right.

While I am here.. Why did you made the change in bsd.mate.mk?

```
#. for component in ${USE_MATE:O:u:C/^([^:]+).*/\1/}
. for component in ${USE_MATE:C/^([^:]+).*/\1/}
#. for component in ${USE_GNOME:C/^([^:]+).*/\1/}
```

You need to leave that one alone unless you have a good reason to make the change. The "O:u:" needs to be there or it will run some dependencies more than twice.

One more thing, why did you remove the "matehack_PRE_PATCH"? The bsd.mate.mk looks so incomplete too when you removed that "matehack_PRE_PATCH".

When you make the change. Please commit one at each change to make commit history more useful for us to understand the reasons why you made change.

**Pull request closed without merging**
