### PR TITLE
commiting mate 1.8.0

### PR DESCRIPTION
**Pull request by ericbsd**
Still have some ports that does not build like mate-applets mate-control-centre mate-screensaver.

I have not mush time to put on some minor or big issue I have a lot on my plate with my job, it is my 17 day of work with out a day of and I have 20 more to do, plus the development of GhostBSD its to mush for the moment, if my clean up is good the only ports that need to work on is mate-applets, mate-control-centre, mate-screensaver.

### CODE REVIEW

**Comment by kwm81** [comment]
Files like share/glib-2.0/schemas/org.mate.Caja.Sendto.gschema.xml should be removed from the plist and put in GLIB_SCHEMAS=org.mate.Caja.Sendto.gschema.xml.
And also mezz comment about a ton of new @dirrmtry's that are still in the plist that belong to mtree or gnomehier.

But since you don't have time to correct this I think we should merge this and then clean them up, is that ok with you mezz?

**Comment by jlmess77** [comment]
If you want to clean up after merge it then it's fine with me. :-)

**Comment by jlmess77** [comment]
Oh by the way, ericbsd, thanks for improvement on it. I hope my feedback will help to improvement better quality of your skill and work with FreeBSD.

**Comment by ericbsd** [comment]
I have learn a lot, sure I will continue to help you guys, but for this
month I can't do much to help.

**Pull request merged**
